name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.6.8
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_firebase_chat_core

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  meta: '>=1.8.0 <2.0.0'

dev_dependencies:
  dart_code_metrics: ^5.7.6
  flutter_lints: '>=3.0.0 <5.0.0'
  flutter_test:
    sdk: flutter
