name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.6.3
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_firebase_chat_core

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  cloud_firestore: ^4.0.1
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.4.3
  meta: ^1.7.0

dev_dependencies:
  dart_code_metrics: ^4.15.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
