name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.4.1
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_firebase_chat_core

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.5.2
  firebase_auth: ^3.1.1
  flutter_chat_types: ^3.1.2
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
